core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.contrib import admin

admin.autodiscover()

# To add a new path, first import the app:
# import blog
#
# Then add the new path:
# path('blog/', blog.urls, name="blog")
#
# Learn more here: https://docs.djangoproject.com/en/2.1/topics/http/urls/

urlpatterns = [
    path("", include('pages.urls')),
    path("workshops/", include('workshops.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import Home, contact

urlpatterns = [
    path("", Home.as_view(), name='home'),
    path("contact", contact, name='contact'),
]

workshops/urls.py
from django.urls import path

from .views import WorkshopDetail

urlpatterns = [
    path("<pk>", WorkshopDetail.as_view(), name='workshop'),
]

category/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

pages/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models

from category.models import Category


class Project(models.Model):
    category = models.ManyToManyField(Category)
    score = models.PositiveIntegerField(blank=True, null=True, default=1)
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(default='project_default.png', upload_to='project_images')
    link = models.URLField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "Projects"
        ordering = ['-score']

    def __str__(self):
        return self.title

workshops/models.py
from django.db import models

from category.models import Category


class Workshop(models.Model):
    category = models.ManyToManyField(Category)
    title = models.CharField(max_length=100)
    description = models.TextField()
    age = models.CharField(max_length=100, blank=True, null=True)
    public = models.CharField(max_length=100, blank=True, null=True)
    value = models.IntegerField(blank=True, null=True)
    link = models.URLField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "workshops"

    def __str__(self):
        return self.title


def get_image_filename(instance, filename):
    image_id = instance.workshop.id
    return f"workshop_images/{image_id}"


class WorkshopImage(models.Model):
    workshop = models.ForeignKey(Workshop, null=True, blank=True, default=None, on_delete=models.SET_NULL)
    image = models.ImageField(upload_to=get_image_filename)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

pages/forms.py
from django import forms
from django.core.mail import send_mail


class ContactForm(forms.Form):
    name = forms.EmailField(required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

category/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.views.generic.base import TemplateView

from category.models import Category
from projects.models import Project


class Home(TemplateView):

    template_name = "pages/home.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['projects'] = Project.objects.filter(active=True)
        context['categories'] = Category.objects.all()
        return context


# FIXME: Change to FormView template and place the alert msgs on top of the page
# TODO: Jquery to post message
def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['message']
        subject = f"Msg from {name}, form in ariedi.com.br"

        send_mail(subject,
                  message,
                  email,
                  ['joaoariedi@gmail.com'],
                  fail_silently=False)
        messages.success(request, 'Thanks, your message is sent successfully.')

    return redirect('home')

projects/views.py
from django.shortcuts import render

# Create your views here.

workshops/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from workshops.models import Workshop


class WorkshopDetail(TemplateView):

    template_name = "workshops/workshop.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workshop'] = Workshop.objects.first()
        return context

templates/base.html
{% load static %}

<!doctype html>
<html lang="en-US">

<!-- Head -->
{% include 'includes/_header.html' %}

<body class="home">

	<!-- Preloader -->
	<div class="preloader">
		<div class="centrize full-width">
			<div class="vertical-center">
				<div class="spinner">
					<div class="double-bounce1"></div>
					<div class="double-bounce2"></div>
				</div>
			</div>
		</div>
	</div>

	<!-- Container -->
	<div class="container">

		<!-- Cursor -->
		<div class="cursor-follower"></div>

        <!-- Navbar -->
        {% include 'includes/_navbar.html' %}

        <!--Main Content Start -->
        {% block content %}
        {% endblock content %}
        <!-- Main Content Ends -->

        <!-- Footer -->
        {% include 'includes/_footer.html' %}

        <!-- Lines -->
		<div class="lines">
			<div class="line-col"></div>
			<div class="line-col"></div>
			<div class="line-col"></div>
			<div class="line-col"></div>
			<div class="line-col"></div>
		</div>

    </div>
</body>

</html>

templates/includes/_footer.html
<!-- Footer -->
<footer class="footer">
    <div class="copy">
        <p>E: joaoariedi@gmail.com</p>
        <p>T: +55 14 98189 5229</p>
    </div>
    <div class="soc-box">
        <div class="follow-label">Follow Me</div>
        <div class="soc">
            <a target="_blank" href="https://www.linkedin.com/in/joaoariedi/">
                <span class="icon fab fa-linkedin"></span>
            </a>
            <a target="_blank" href="https://github.com/glitchman23">
                <span class="icon fab fa-github"></span>
            </a>
        </div>
    </div>
    <div class="clear"></div>
</footer>

{% include 'includes/_scripts.html' %}
{% block extrascripts %}{% endblock extrascripts %}

templates/includes/_header.html
{% load static %}

<head>
	<!-- Meta -->
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
	<meta name="description" content="John Ariedi, Organizational Intelligence Manager and Python Developer" />
	<meta name="keywords" content="data mining, data analytics, ETL, Python, resume, cv" />
	<meta name="author" content="John Ariedi" />

	<!-- Title -->
	<title>Ariedi - Organizational Intelligence </title>

    {% include "includes/_styles.html" %}

    <link rel="shortcut icon" href={% static "images/favicons/fav2.png" %}>

</head>

templates/includes/_navbar.html
<!-- Header -->
<header class="header">
    <div class="head-top">

        <!-- menu button -->
        <a href="" class="menu-btn"><span></span></a>

        <!-- logo -->
        <div class="logo hover-masks-logo">
            <a href={% url 'home' %}>
                <span class="mask-lnk">John <strong>Ariedi</strong></span>
                <span class="mask-lnk mask-lnk-hover">João <strong>Ariedi</strong></span>
            </a>
        </div>

        <!-- top menu -->
        <div class="top-menu hover-masks">
            <div class="top-menu-nav">
                <div class="menu-topmenu-container">
                    <ul class="menu">
                        {% if request.path == '/' %}
                        <li class="menu-item current-menu-item">
                            <a href="#section-started">Home</a>
                        </li>
                        <li class="menu-item">
                            <a href="#section-services">Service</a>
                        </li>
                        <li class="menu-item">
                            <a href="#section-history">Resume</a>
                        </li>
                        <li class="menu-item">
                            <a href="#section-skills">Skills</a>
                        </li>
                        <li class="menu-item">
                            <a href="#section-portfolio">Projects</a>
                        </li>
                        <li class="menu-item">
                            <a href="#section-contacts">Contact</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>

    </div>
</header>

templates/includes/_scripts.html
{% load static %}

{% block scripts %}

    <!-- Scripts -->
	<script src={% static "js/jquery.min.js" %}></script>
	<script src={% static "js/jquery.validate.js" %}></script>
	<script src={% static "js/magnific-popup.js" %}></script>
	<script src={% static "js/simpleParallax.js" %}></script>
	<script src={% static "js/typed.js" %}></script>
	<script src={% static "js/jarallax.js" %}></script>
	<script src={% static "js/jarallax-video.js" %}></script>
	<script src={% static "js/jarallax-element.js" %}></script>
	<script src={% static "js/imagesloaded.pkgd.js" %}></script>
	<script src={% static "js/isotope.pkgd.js" %}></script>
	<script src={% static "js/swiper.js" %}></script>
	<script src={% static "js/grained.js" %}></script>

	<script src={% static "js/scripts.js" %}></script>

{% endblock scripts %}

templates/includes/_styles.html
{% load static %}

	<!-- Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap&subset=cyrillic" rel="stylesheet">

	<!-- Styles -->
	<link rel="stylesheet" href={% static "css/basic.css" %} />
	<link rel="stylesheet" href={% static "css/layout.css" %} />
	<link rel="stylesheet" href={% static "css/magnific-popup.css" %} />
	<link rel="stylesheet" href={% static "css/animate.css" %} />
	<link rel="stylesheet" href={% static "css/jarallax.css" %} />
	<link rel="stylesheet" href={% static "css/swiper.css" %} />
	<link rel="stylesheet" href={% static "css/fontawesome.css" %} />
	<link rel="stylesheet" href={% static "css/brands.css" %} />
	<link rel="stylesheet" href={% static "css/solid.css" %} />
	<link rel="stylesheet" href={% static "css/theme-colors/blue.css" %} />


{% block styles %}

{% endblock styles %}

workshops/templates/workshops/workshop.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <!-- Wrapper -->
    <div class="wrapper">

        <!-- Section Started -->
        <div class="section started layout-creative" id="section-started">

            <!-- background -->
            <div class="video-bg">
                <div class="video-bg-mask"></div>
                <div class="video-bg-texture" id="grained_container"></div>
            </div>

            <!-- started content -->
            <div class="centrize full-width">
                <div class="vertical-center">
                    <div class="started-content">
                        <h1 class="h-title">{{ workshop.title }}</h1>
                        <div class="h-subtitles">
                            <div class="h-subtitle typing-bread">
                                <p class="breadcrumbs">
                                    <a href={% url 'home' %}>Home</a> / Oficina de contrução de telescópio
                                </p>
                            </div>
                            <span class="typed-bread"></span>
                        </div>
                    </div>
                </div>
            </div>

            <!-- mosue button -->
            <a href="#" class="mouse_btn" style="display: none;"><span class="icon fas fa-chevron-down"></span></a>

        </div>

        <!-- Work Single -->
        <div class="section blog">
            <div class="content content-box">
                <div class="single-post-text">

                    <!-- portfolio content -->
                    <div class="portfolio-info portfolio-cols">
                        <div class="description-col">

                            <!-- title -->
                            <div class="title">
                                <div class="title_inner">Descrição</div>
                            </div>

                            <!-- text -->
                            <div class="single-post-text">

                                {{ workshop.description | safe }}


                                {% if workshop.link %}
                                <a class="btn hover-animated" href={{ workshop.link }} >
                                    <span class="circle"></span>
                                    <span class="lnk">Projeto completo</span>
                                </a>
                                {% endif %}

                                <!-- gallery -->
                                <div class="gallery-item">
                                    {% for workshop_image in workshop.workshopimage_set.all %}
                                    <p>
                                        <a href={{ workshop_image.image.url }}>
                                            <img alt="workshop images" src={{ workshop_image.image.url }}/>
                                        </a>
                                    </p>
                                    {% endfor %}
                                </div>
                            </div>

                        </div>
                        <div class="details-col">

                            <!-- title -->
                            <div class="title">
                                <div class="title_inner">Detalhes</div>
                            </div>

                            <!-- details -->
                            <ul class="details-list">
                                <li><strong>Categorias</strong> {{ workshop.category.first }}</li>
                                <li><strong>Idade</strong> {{ workshop.age }}</li>
                                <li><strong>Público</strong> {{ workshop.public }}</li>
                                <li><strong>Custo</strong> R$ {{ workshop.value }}</li>
                            </ul>

                        </div>
                    </div>

                </div>
                <div class="clear"></div>
            </div>
        </div>

    </div>

{% endblock content %}